=== ZocoLini/dam-2/adat/A4UD2Vinculacion_Borja_Castellano_Extremadouro/Modulo.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="Modulo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element type="xsd:string" name="Nome"/>
                <xsd:element type="tipoContidos" name="Contidos"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="tipoContidos">
        <xsd:sequence>
            <xsd:element type="tipoBloque" name="Bloque" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="tipoBloque">
        <xsd:sequence>
            <xsd:element type="xsd:string" name="Titulo" />
            <xsd:element type="xsd:string" name="Descripcion" />
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="sesions" />
        <xsd:attribute type="xsd:string" name="num" />
    </xsd:complexType>
</xsd:schema>

=== ZocoLini/dam-2/adat/A4UD2Vinculacion_Borja_Castellano_Extremadouro/modulo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Modulo xsl:noNamespaceSchemaLocation="Modulo.xsd" xmlns:xsl="http://www.w3.org/2001/XMLSchema-instance">
    <Nome>Redes de Área Local</Nome>
    <Contidos>
        <Bloque sesions="60" num="1">
            <Titulo>Sistemas de comunicacións</Titulo>
            <Descripcion>Aspectos físicos, procolos e arquitecturas de redes</Descripcion>
        </Bloque>
        <Bloque sesions="50" num="2">
            <Titulo>Redes de datos</Titulo>
            <Descripcion>Dispositivos de interconexión de redes locais e de área extensa</Descripcion>
        </Bloque>
        <Bloque sesions="90" num="3">
            <Titulo>Redes de área local</Titulo>
            <Descripcion>Administración e xestión dunha rede de área local.</Descripcion>
        </Bloque>
        <Bloque sesions="60" num="4">
            <Titulo>Servizos de Internet</Titulo>
            <Descripcion>Adm. de servizos que empreguen protocolos estándar en Internet</Descripcion>
        </Bloque>
    </Contidos>
</Modulo>
